targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern: "ViewModel$"
          file_name_pattern: "_view_model$"
