name: rx_mvvm_builder
description: Reactive MVVM Pattern Builder
version: 1.0.0
maintainer: Filipe Santiago (@feelssantiago)
homepage: https://github.com/feelsantiago/rx_mvvm
documentation:

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.0
  flutter:
    sdk: flutter
  source_gen: ^1.3.2
  rx_mvvm_annotations:
    ^1.0.0
    # path: ../rx_mvvm_annotations
  collection: ^1.17.1
  oxidized: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  test: ^1.24.1
  mockito: ^5.4.1
  build_runner: ^2.4.4
