name: rx_mvvm_annotations
description: Reactive MVVM Pattern Annotations
version: 1.0.0
maintainer: Filipe Santiago (@feelssantiago)
authors:
  - Filipe Santiago <porto.santiago@hotmail.com>
homepage: https://github.com/feelsantiago/rx_mvvm
documentation:

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
