name: rx_mvvm
description: Reactive MVVM Pattern
version: 1.0.0
maintainer: Filipe Santiago (@feelssantiago)
homepage: https://github.com/feelsantiago/rx_mvvm
documentation:

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rx_mvvm_annotations: ^1.0.0
    # path: ../rx_mvvm_annotations
  focus_detector: ^2.0.1
  get_it: ^7.6.0
  rx_command: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
